# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=30, verbose_name='航班')),
                ('status', models.CharField(max_length=30, verbose_name='状态')),
                ('beginPlace', models.CharField(max_length=30, verbose_name='始发地')),
                ('planarrtime', models.TimeField(verbose_name='计划到达')),
                ('arrtime', models.CharField(max_length=30, verbose_name='实际到达')),
                ('arrplace', models.CharField(max_length=10, verbose_name='到达航站楼')),
                ('bagplace', models.CharField(max_length=20, verbose_name='行李转盘')),
            ],
            options={
                'verbose_name_plural': '进港',
                'db_table': 'getIn',
            },
        ),
        migrations.CreateModel(
            name='left',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=30, verbose_name='航班')),
                ('status', models.CharField(max_length=30, verbose_name='状态')),
                ('beginPlace', models.CharField(max_length=30, verbose_name='始发地')),
                ('planarrtime', models.TimeField(verbose_name='计划到达')),
                ('arrtime', models.CharField(max_length=30, verbose_name='实际到达')),
                ('arrplace', models.CharField(max_length=10, verbose_name='到达航站楼')),
                ('bagplace', models.CharField(max_length=20, verbose_name='行李转盘')),
            ],
            options={
                'verbose_name_plural': '离港',
                'db_table': 'left',
            },
        ),
    ]
