# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-27 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='left',
        ),
    ]
