# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_delete_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='left',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights', models.CharField(max_length=30, verbose_name='航班')),
                ('statu', models.CharField(max_length=30, verbose_name='状态')),
                ('beginPlaces', models.CharField(max_length=30, verbose_name='始发地')),
                ('planarrtimes', models.TimeField(verbose_name='计划到达')),
                ('arrtimes', models.CharField(max_length=30, verbose_name='实际到达')),
                ('arrplaces', models.CharField(max_length=10, verbose_name='到达航站楼')),
                ('bagplaces', models.CharField(max_length=20, verbose_name='行李转盘')),
            ],
            options={
                'verbose_name_plural': '离港',
                'db_table': 'left',
            },
        ),
    ]
