# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-27 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0005_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='left',
            old_name='arrplaces',
            new_name='arrplace',
        ),
        migrations.RenameField(
            model_name='left',
            old_name='arrtimes',
            new_name='arrtime',
        ),
        migrations.RenameField(
            model_name='left',
            old_name='bagplaces',
            new_name='bagplace',
        ),
        migrations.RenameField(
            model_name='left',
            old_name='beginPlaces',
            new_name='beginPlace',
        ),
        migrations.RenameField(
            model_name='left',
            old_name='flights',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='left',
            old_name='planarrtimes',
            new_name='planarrtime',
        ),
        migrations.RenameField(
            model_name='left',
            old_name='statu',
            new_name='status',
        ),
    ]
