# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0006_auto_20191027_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logname', models.CharField(max_length=50, verbose_name='登录名')),
                ('username', models.CharField(max_length=50, verbose_name='使用名')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
                'db_table': 'user',
            },
        ),
    ]
