# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0007_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='logname',
            new_name='log_name',
        ),
    ]
