# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0008_auto_20191028_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='user',
        ),
    ]
