# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0009_auto_20191028_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginplace', models.CharField(max_length=100, verbose_name='始发地')),
                ('endplace', models.CharField(max_length=100, verbose_name='终点')),
                ('money', models.CharField(max_length=50, verbose_name='价格')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': '机票',
                'db_table': 'planeticketes',
            },
        ),
    ]
