# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0011_auto_20191028_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginplace', models.CharField(max_length=100, verbose_name='始发地')),
                ('endplace', models.CharField(max_length=100, verbose_name='终点')),
                ('money', models.CharField(max_length=50, verbose_name='价格')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': '机票',
                'db_table': 'planeticketes',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=50, verbose_name='登录名')),
                ('username', models.CharField(max_length=50, verbose_name='使用名')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('tic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.tickets')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
                'db_table': 'user',
            },
        ),
    ]
