# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0012_tickets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.tickets'),
        ),
    ]
