# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0013_auto_20191028_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='位置')),
                ('infor', models.CharField(max_length=100, verbose_name='信息')),
            ],
            options={
                'verbose_name_plural': '机票',
                'db_table': 'planetickete',
            },
        ),
    ]
