# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-31 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0014_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name_plural': '失误'},
        ),
    ]
