# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-31 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0015_auto_20191031_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
