# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-08 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0019_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.ticket'),
        ),
    ]
